version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode

issues:
  exclude-rules:
    - linters:
        - errcheck
      source: "defer "
    - linters:
        - errcheck
      path: _test\.go
