package apitest

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/voilelab/plainshelf/server"
)

// WriteLogFile seeds a file the log API is expected to list, or to ignore.
func WriteLogFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile %s: %v", filepath.Base(path), err)
	}
}

// LogEntryByFilename finds the listed entry for a seeded file, since its ID is
// generated by the server rather than derived from the name.
func LogEntryByFilename(t *testing.T, env *Env, filename string) server.LogFileEntry {
	t.Helper()

	for _, entry := range GetJSON[[]server.LogFileEntry](t, env, LogURL()) {
		if entry.Filename == filename {
			return entry
		}
	}
	t.Fatalf("log list is missing the seeded file %s", filename)
	return server.LogFileEntry{}
}
