package contract_test

import (
	"net/http"
	"slices"
	"strings"
	"testing"

	"github.com/voilelab/plainshelf/server/contract/apitest"

	"github.com/voilelab/plainshelf/server"
)

func TestAPICreateBookSourceContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Source Book", "", "src.txt", "content")

	// Creating a source on a nonexistent book should return 404.
	rec := env.Post(apitest.BookURL("no-such-book", "sources"), nil)
	apitest.AssertStatus(t, rec, http.StatusNotFound)

	// Creating a source returns 200 with the new source metadata, and the new
	// source appears in the list.
	newSourceID := apitest.CreateBookSource(t, env, created.Meta.ID)
	if ids := apitest.SourceIDs(t, env, created.Meta.ID); !slices.Contains(ids, newSourceID) {
		t.Fatalf("newly created source %q not found in list: %#v", newSourceID, ids)
	}

	// A derived source uses JSON so Wails does not have to stream generated
	// multipart data through WebKit's custom-scheme handler. Creation and
	// optional activation still happen atomically in one request.
	derivedBody := `{"content":"# Book\n\n## One\nBody 🍥","format":"md","comment":"derived in contract test","set_current":true}`
	rec = env.RequestTyped(http.MethodPost, apitest.BookURL(created.Meta.ID, "sources"),
		"application/json; charset=utf-8", strings.NewReader(derivedBody))
	apitest.AssertStatus(t, rec, http.StatusOK)
	derived := apitest.DecodeJSON[map[string]any](t, rec)
	derivedID, _ := derived["id"].(string)
	if derived["format"] != "md" || derived["schema_version"] != float64(1) {
		t.Fatalf("derived source metadata = %#v, want schema 1 Markdown", derived)
	}
	if derived["comment"] != "derived in contract test" {
		t.Fatalf("derived source comment = %#v", derived["comment"])
	}

	contentRec := env.Get(apitest.SourceURL(created.Meta.ID, derivedID, "content"))
	apitest.AssertStatus(t, contentRec, http.StatusOK)
	if got := contentRec.Body.String(); got != "# Book\n\n## One\nBody 🍥" {
		t.Fatalf("derived source content = %q", got)
	}

	// Keep accepting multipart requests from clients released before the JSON
	// transport was introduced.
	legacyUpload := apitest.FormUpload{
		Fields: [][2]string{
			{"format", "txt"},
			{"comment", "legacy multipart client"},
		},
		FileField:   "content",
		Filename:    "source.txt",
		ContentType: "application/octet-stream",
		Content:     "legacy body",
	}
	rec = env.Do(legacyUpload.Request(t, http.MethodPost, apitest.BookURL(created.Meta.ID, "sources")))
	apitest.AssertStatus(t, rec, http.StatusOK)

	activated := apitest.GetJSON[server.Book](t, env, apitest.BookURL(created.Meta.ID))
	if activated.Meta == nil || activated.Meta.CurrentSource != derivedID || activated.Meta.Format != "md" {
		t.Fatalf("activated book = %#v, want current derived Markdown source", activated.Meta)
	}
}

func TestAPIDeleteBookSourceContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Delete Source Book", "", "del.txt", "content")
	newSourceID := apitest.CreateBookSource(t, env, created.Meta.ID)

	// Deleting the source should succeed, and it should leave the list.
	rec := env.Delete(apitest.SourceURL(created.Meta.ID, newSourceID))
	apitest.AssertStatus(t, rec, http.StatusNoContent)
	if ids := apitest.SourceIDs(t, env, created.Meta.ID); slices.Contains(ids, newSourceID) {
		t.Fatalf("deleted source %q still present in list", newSourceID)
	}

	// Deleting a nonexistent source, or a source of a nonexistent book, is a 404.
	rec = env.Delete(apitest.SourceURL(created.Meta.ID, "nonexistent-source"))
	apitest.AssertStatus(t, rec, http.StatusNotFound)
	rec = env.Delete(apitest.SourceURL("no-such-book", newSourceID))
	apitest.AssertStatus(t, rec, http.StatusNotFound)
}

// TestAPIDeleteBookSourceCommentContract pins the one thing a client may do to
// an import note: remove it. The note is generated by the importer or a
// conversion, so the API offers deletion and no rewrite.
func TestAPIDeleteBookSourceCommentContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Comment Source Book", "", "note.txt", "content")

	body := `{"content":"noted","format":"txt","comment":"Regex chapter conversion of 20260523-234949"}`
	rec := env.RequestTyped(http.MethodPost, apitest.BookURL(created.Meta.ID, "sources"),
		"application/json; charset=utf-8", strings.NewReader(body))
	apitest.AssertStatus(t, rec, http.StatusOK)
	sourceID, _ := apitest.DecodeJSON[map[string]any](t, rec)["id"].(string)

	rec = env.Delete(apitest.SourceURL(created.Meta.ID, sourceID, "comment"))
	apitest.AssertStatus(t, rec, http.StatusNoContent)

	// The note is gone from the source, and nothing else about it moved.
	meta := apitest.GetJSON[map[string]any](t, env, apitest.SourceURL(created.Meta.ID, sourceID))
	if meta["comment"] != "" {
		t.Fatalf("comment after delete = %#v, want empty", meta["comment"])
	}
	if got, _ := meta["id"].(string); got != sourceID {
		t.Fatalf("source id after delete = %q, want %q", got, sourceID)
	}
	if meta["format"] != "txt" {
		t.Fatalf("source format after delete = %#v, want txt", meta["format"])
	}

	// Deleting a note that is already gone is the same no-op success, so a
	// client that retries does not have to tell the two cases apart.
	apitest.AssertStatus(t, env.Delete(apitest.SourceURL(created.Meta.ID, sourceID, "comment")), http.StatusNoContent)

	// A nonexistent source, or a nonexistent book, is a 404.
	apitest.AssertStatus(t, env.Delete(apitest.SourceURL(created.Meta.ID, "nonexistent-source", "comment")), http.StatusNotFound)
	apitest.AssertStatus(t, env.Delete(apitest.SourceURL("no-such-book", sourceID, "comment")), http.StatusNotFound)
}

func TestAPISetCurrentBookSourceContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Set Current Source Book", "", "src.txt", "content")
	newSourceID := apitest.CreateBookSource(t, env, created.Meta.ID)

	// Setting the current source should succeed.
	rec := env.Put(apitest.SourceURL(created.Meta.ID, newSourceID, "current"), nil)
	apitest.AssertStatus(t, rec, http.StatusNoContent)

	// The book should reflect the new current source.
	bookData := apitest.GetJSON[map[string]any](t, env, apitest.BookURL(created.Meta.ID))
	meta, _ := bookData["meta"].(map[string]any)
	if currentSource, _ := meta["current_source"].(string); currentSource != newSourceID {
		t.Fatalf("expected current_source %q, got %q", newSourceID, currentSource)
	}

	// A nonexistent source, or a nonexistent book, is a 404.
	rec = env.Put(apitest.SourceURL(created.Meta.ID, "nonexistent-source", "current"), nil)
	apitest.AssertStatus(t, rec, http.StatusNotFound)
	rec = env.Put(apitest.SourceURL("no-such-book", newSourceID, "current"), nil)
	apitest.AssertStatus(t, rec, http.StatusNotFound)
}

func TestAPIRefreshBookSourceMetaContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Refresh Source", "", "refresh.txt", "line one\nline two\nline three")
	sourceID := created.Meta.CurrentSource

	rec := env.Post(apitest.SourceURL(created.Meta.ID, sourceID, "refresh"), nil)
	apitest.AssertStatus(t, rec, http.StatusOK)
	apitest.AssertJSONContentType(t, rec)
	meta := apitest.DecodeJSON[map[string]any](t, rec)
	if id, _ := meta["id"].(string); id != sourceID {
		t.Fatalf("refreshed source id = %q, want %q", id, sourceID)
	}
	if lc, _ := meta["line_count"].(float64); lc <= 0 {
		t.Fatalf("line_count = %v, want > 0", lc)
	}
	if cc, _ := meta["char_count"].(float64); cc <= 0 {
		t.Fatalf("char_count = %v, want > 0", cc)
	}

	// Refreshing a nonexistent source, or a source of a nonexistent book, is a 404.
	rec = env.Post(apitest.SourceURL(created.Meta.ID, "nonexistent", "refresh"), nil)
	apitest.AssertStatus(t, rec, http.StatusNotFound)
	rec = env.Post(apitest.SourceURL("no-such-book", sourceID, "refresh"), nil)
	apitest.AssertStatus(t, rec, http.StatusNotFound)
}

// TestAPIDeleteCurrentBookSourceContract pins the promise that deleting the
// active source leaves a readable book: the pointer moves to a source that
// exists instead of being left dangling, which used to fail every read.
func TestAPIDeleteCurrentBookSourceContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Delete Current Source", "", "cur.txt", "imported body")
	importedID := created.Meta.CurrentSource

	newSourceID := apitest.CreateBookSource(t, env, created.Meta.ID)
	rec := env.Put(apitest.SourceURL(created.Meta.ID, newSourceID, "current"), nil)
	apitest.AssertStatus(t, rec, http.StatusNoContent)

	rec = env.Delete(apitest.SourceURL(created.Meta.ID, newSourceID))
	apitest.AssertStatus(t, rec, http.StatusNoContent)

	if got := apitest.CurrentSourceOf(t, env, created.Meta.ID); got != importedID {
		t.Fatalf("current_source = %q, want the surviving source %q", got, importedID)
	}
	if ids := apitest.SourceIDs(t, env, created.Meta.ID); !slices.Equal(ids, []string{importedID}) {
		t.Fatalf("sources = %#v, want only %q", ids, importedID)
	}
	apitest.AssertStatus(t, env.Get(apitest.BookURL(created.Meta.ID, "content")), http.StatusOK)
}

// TestAPIDeleteLastBookSourceContract pins the other half: a book always keeps
// at least one source, so deleting the only one leaves an empty replacement
// rather than a book with nothing to read.
func TestAPIDeleteLastBookSourceContract(t *testing.T) {
	env := apitest.New(t)
	created := apitest.ImportTextBook(t, env, "Delete Last Source", "", "last.txt", "imported body")
	importedID := created.Meta.CurrentSource

	rec := env.Delete(apitest.SourceURL(created.Meta.ID, importedID))
	apitest.AssertStatus(t, rec, http.StatusNoContent)

	ids := apitest.SourceIDs(t, env, created.Meta.ID)
	if len(ids) != 1 {
		t.Fatalf("sources = %#v, want exactly the empty replacement", ids)
	}
	if ids[0] == importedID {
		t.Fatalf("replacement reused the deleted source ID %q", importedID)
	}
	if got := apitest.CurrentSourceOf(t, env, created.Meta.ID); got != ids[0] {
		t.Fatalf("current_source = %q, want the replacement %q", got, ids[0])
	}

	content := env.Get(apitest.BookURL(created.Meta.ID, "content"))
	apitest.AssertStatus(t, content, http.StatusOK)
	if body := content.Body.String(); body != "" {
		t.Fatalf("content = %q, want the replacement to be empty", body)
	}
}
