package contract_test

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/voilelab/plainshelf/server"
)

func logURL(elem ...string) string {
	return strings.Join(append([]string{"/api/logs"}, elem...), "/")
}

// writeLogFile seeds a file the log API is expected to list, or to ignore.
func writeLogFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile %s: %v", filepath.Base(path), err)
	}
}

// logEntryByFilename finds the listed entry for a seeded file, since its ID is
// generated by the server rather than derived from the name.
func logEntryByFilename(t *testing.T, env *apiTestEnv, filename string) server.LogFileEntry {
	t.Helper()

	for _, entry := range getJSON[[]server.LogFileEntry](t, env, logURL()) {
		if entry.Filename == filename {
			return entry
		}
	}
	t.Fatalf("log list is missing the seeded file %s", filename)
	return server.LogFileEntry{}
}

func TestAPIGetLogsContract(t *testing.T) {
	appLogFile := filepath.Join(t.TempDir(), "app.log")
	shelfLogDir := t.TempDir()

	// The app is left unstarted so the only log files are the seeded ones.
	env := newUnstartedAPITestEnv(t, withAppLogFile(appLogFile), withShelfLogDir(shelfLogDir, "shelf"))

	writeLogFile(t, appLogFile, "app log")
	appLogTime := time.Date(2024, 1, 3, 12, 0, 0, 0, time.UTC)
	if err := os.Chtimes(appLogFile, appLogTime, appLogTime); err != nil {
		t.Fatalf("Chtimes app log: %v", err)
	}
	writeLogFile(t, filepath.Join(shelfLogDir, "shelf-2024-01-02.log"), "shelf log")

	// A file that does not look like a log is not listed.
	writeLogFile(t, filepath.Join(shelfLogDir, "ignore.txt"), "nope")

	rec := env.get(logURL())
	assertStatus(t, rec, http.StatusOK)
	assertJSONContentType(t, rec)

	logs := decodeJSON[[]server.LogFileEntry](t, rec)
	if len(logs) != 2 {
		t.Fatalf("log count = %d, want 2", len(logs))
	}

	if logs[0].ID == "" || logs[0].Source != "logger" || logs[0].Filename != "app.log" || logs[0].Date == "" {
		t.Fatalf("first log = %#v, want app logger entry", logs[0])
	}
	if logs[1].ID == "" || logs[1].Source != "shelves[0].shelfconf.logger" || logs[1].Filename != "shelf-2024-01-02.log" || logs[1].Date != "2024-01-02" {
		t.Fatalf("second log = %#v, want shelf logger entry", logs[1])
	}
}

func TestAPIGetLogContentContract(t *testing.T) {
	logDir := t.TempDir()
	env := newUnstartedAPITestEnv(t, withAppLogDir(logDir, "app"))

	writeLogFile(t, filepath.Join(logDir, "app-2024-01-02.log"), "line 1\nline 2\n")

	target := logEntryByFilename(t, env, "app-2024-01-02.log")

	rec := env.get(logURL(target.ID, "content"))
	assertStatus(t, rec, http.StatusOK)
	assertContentType(t, rec, plainTextContentType)
	if got := rec.Body.String(); got != "line 1\nline 2\n" {
		t.Fatalf("content = %q, want seeded log content", got)
	}

	rec = env.get(logURL("missing", "content"))
	assertStatus(t, rec, http.StatusNotFound)
}

// The log API stays behind the token whatever protect_read says: a log records
// every request path, access time and remote address, which is the shelf's
// structure and its usage rather than the books a reader came for.
func TestAPILogsRequireTokenWithoutProtectReadContract(t *testing.T) {
	logDir := t.TempDir()
	security := localTokenSecurity()
	security.ProtectRead = false
	env := newUnstartedAPITestEnv(t, withAppLogDir(logDir, "app"), withSecurity(security))

	writeLogFile(t, filepath.Join(logDir, "app-2024-01-02.log"), "line 1\n")

	rec := env.doRaw(httptest.NewRequest(http.MethodGet, logURL(), nil))
	assertStatus(t, rec, http.StatusUnauthorized)

	// An ordinary read is still open, so this is the log routes being excepted
	// rather than protect_read having been ignored. A setting is read instead of
	// the book list because this env is deliberately unstarted, and a shelf that
	// has not finished its initial scan answers 503.
	rec = env.doRaw(httptest.NewRequest(http.MethodGet, settingPath, nil))
	assertStatus(t, rec, http.StatusOK)

	// With the token the page works unchanged.
	target := logEntryByFilename(t, env, "app-2024-01-02.log")

	rec = env.doRaw(httptest.NewRequest(http.MethodGet, logURL(target.ID, "content"), nil))
	assertStatus(t, rec, http.StatusUnauthorized)

	rec = env.get(logURL(target.ID, "content"))
	assertStatus(t, rec, http.StatusOK)
	if got := rec.Body.String(); got != "line 1\n" {
		t.Fatalf("content = %q, want seeded log content", got)
	}
}

// Security mode "none" is an explicit "do not authenticate", so the exception
// above does not reintroduce a gate the operator turned off.
func TestAPILogsOpenUnderSecurityModeNoneContract(t *testing.T) {
	logDir := t.TempDir()
	env := newUnstartedAPITestEnv(t,
		withAppLogDir(logDir, "app"),
		withSecurity(&server.SecurityConf{Mode: server.SecurityModeNone}))

	writeLogFile(t, filepath.Join(logDir, "app-2024-01-02.log"), "line 1\n")

	rec := env.doRaw(httptest.NewRequest(http.MethodGet, logURL(), nil))
	assertStatus(t, rec, http.StatusOK)
}
